export const projectsData = [
  {
    name: "Password-Manager-App",
    version: "2.1",
    testLink: "https://www.google.com",
    uat: "1.23",
    liveLink: "https://www.google.com",
  },
  {
    name: "Task-Tracker",
    version: "1.5",
    testLink: "https://example.com/test-task-tracker",
    uat: "1.10",
    liveLink: "https://example.com/live-task-tracker",
  },
  {
    name: "E-Commerce-Platform",
    version: "3.2",
    testLink: "https://example.com/test-ecommerce",
    uat: "2.8",
    liveLink: "https://example.com/live-ecommerce",
  },
  {
    name: "Blog-CMS",
    version: "4.0",
    testLink: "https://example.com/test-blog",
    uat: "3.7",
    liveLink: "https://example.com/live-blog",
  },
  {
    name: "Social-Media-App",
    version: "2.7",
    testLink: "https://example.com/test-social",
    uat: "2.5",
    liveLink: "https://example.com/live-social",
  },
  {
    name: "Portfolio-Site",
    version: "1.0",
    testLink: "https://example.com/test-portfolio",
    uat: "1.0",
    liveLink: "https://example.com/live-portfolio",
  },
  {
    name: "Chat-Application",
    version: "3.5",
    testLink: "https://example.com/test-chat",
    uat: "3.3",
    liveLink: "https://example.com/live-chat",
  },
  {
    name: "Weather-Dashboard",
    version: "2.2",
    testLink: "https://example.com/test-weather",
    uat: "2.1",
    liveLink: "https://example.com/live-weather",
  },
  {
    name: "Finance-Tracker",
    version: "1.8",
    testLink: "https://example.com/test-finance",
    uat: "1.7",
    liveLink: "https://example.com/live-finance",
  },
  {
    name: "Health-Monitoring-App",
    version: "3.0",
    testLink: "https://example.com/test-health",
    uat: "2.9",
    liveLink: "https://example.com/live-health",
  },
];
